{
  "auth": {
    "healthy": true,
    "details": {
      "message": "Running in DEBUG_MODE with mock data",
      "mode": "debug",
      "status": "healthy"
    },
    "checked_at": "2025-05-07T15:14:26.799995"
  },
  "cart": {
    "healthy": true,
    "details": {
      "service": "cart",
      "status": "healthy"
    },
    "checked_at": "2025-05-07T15:14:26.799995"
  },
  "profile": {
    "healthy": true,
    "details": {
      "message": "Running in DEBUG_MODE with mock data",
      "mode": "debug",
      "status": "healthy"
    },
    "checked_at": "2025-05-07T15:14:26.799995"
  },
  "order": {
    "healthy": true,
    "details": {
      "service": "order",
      "status": "healthy"
    },
    "checked_at": "2025-05-07T15:14:26.799995"
  },
  "customer-support": {
    "healthy": false,
    "details": "HTTPConnectionPool(host='localhost', port=5004): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72449fef15b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "checked_at": "2025-05-07T15:14:26.799995"
  },
  "product": {
    "healthy": false,
    "details": "HTTPConnectionPool(host='localhost', port=5006): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72449fee6fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "checked_at": "2025-05-07T15:14:26.799995"
  },
  "overall_status": "degraded"
}